### PR TITLE
Fix bug in record commands

### PR DESCRIPTION
**Pull request by Steback**
Hi, I use your code to learn how to implement ImGui in Vulkan, but when I run the code, the ImGui interface is not visible and the triangle is not rendered correctly. I found that the error probably was caused in the record commands. So I change the ImGui draw function to the same command pool and command buffer as the triangle. I hope this solution are good, thanks!

### CODE REVIEW

**Comment by tstullich** [comment]
Ok, thanks! I’ll take a look the next couple of days and provide some feedback

**Comment by tstullich** [comment]
Hey @Steback, I just got a chance to look over your PR. Would you mind changing the commit so that only code related to the bug is pulled in?

I see you have made your own modifications to file locations and upgraded DearImGUI, which you are definitely welcome to do, but it's a lot easier to focus on the buffer recording issue with those changes out of the way. Otherwise it becomes harder for me to take steps to reproduce your issue.

**Comment by Steback** [comment]
Ok, I will make the change

**Comment by Steback** [comment]
@tstullich Hey! I see the last commit you do solve the bug. Thank you!.

**Comment by tstullich** [comment]
Ok, great! If anything else comes up please let me know. I'll close out the issue for now then.

**Pull request closed without merging**
